[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "panda==0.3.1",
    "pandas==2.2.3",
    "scikit-learn==1.5.2",
]
