
[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "matplotlib==3.9.3",
    "pandas>=2.0.0",
    "streamlit>=1.30.0",
    "scikit-learn>=1.3.0"
]
